$(function() {
	var $ometa =
		$('<div class="ometa bg-1 padding-small">')
			.append($('<div class="row">')
				.append('<input class="full-width" type="text" value="Lisp"/>'))
			.append($('<div class="row">')
				.append($('<div class="row ometa-non-terminal margin-vertical-large margin-left-large">')
					.append($('<div class="column width-gutter">')
						.append($('<button class="hover-visible">').html('+')))
					.append($('<div class="column ometa-def">')
						.append($('<input class="full-width" type="text"/>').val('ev'))
						.append($('<table class="full-width">')
							.append($('<tbody>')
								.append($('<tr>')
									.append($('<td colspan=3>')
								.append($('<tr>')
									.append($('<td>')
										.append($('<div class="row">')
											.append($('<button class="hover-visible">').html('+'))
											.append('Pattern'))
										.append($('<textarea>').val('string:a')))
									.append($('<td>')
										.append('<div class="row">Callback</div>')
										.append($('<textarea>').val('self.env[a]')))
									.append($('<td>')
										.append('<div class="row"></div>')
										.append($('<button>').html('-'))))
								.append($('<tr>')
									.append($('<td colspan=3>')
										.append($('<button class="hover-visible">').html('+')))))))))
				.append($('<div class="row">')
					.append($('<button class="hover-visible">').html('+')))))
	
	$ometa.appendTo('body')
});
